### ISSUE TITLE
My MAC is OS X EI Capitan 10.11 installation script appeared error

### ISSUE THREAD

**Issue by XieXieZhongxi** [MarcusSmith/ipaHelper#89] opened 2015-09-16 16:08 UTC
<img width="420" alt="qq20150917-1 2x" src="https://cloud.githubusercontent.com/assets/8802276/9910450/c8f88b40-5ccf-11e5-9e25-696c411b0e4a.png">
<img width="586" alt="qq20150917-2 2x" src="https://cloud.githubusercontent.com/assets/8802276/9910559/2ee86c72-5cd0-11e5-8ffb-56f16dfa4ae5.png">

**Comment by MarcusSmith** [comment] 2016-05-02 17:55
Duplicate of #86

**Closed by MarcusSmith** 2016-05-02 17:55 UTC
